{% set name = "mplsoccer" %}
{% set version = "1.2.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/mplsoccer-{{ version }}.tar.gz
  sha256: e163cb0d02f80a77b210ec789383932a2edf30bdac59cc7fa45ed69e41160901

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - hatch
    - python >=3.7
    - pip
  run:
    - python >=3.7
    - matplotlib-base >=3.6
    - numpy
    - pandas
    - pillow
    - requests
    - scipy
    - seaborn

test:
  imports:
    - mplsoccer
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://pypi.org/project/mplsoccer/
  summary: Football pitch plotting library for matplotlib
  dev_url: https://github.com/andrewRowlinson/mplsoccer
  doc_url: https://mplsoccer.readthedocs.io/en/latest/
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - andrewRowlinson
