{% set name = "mplsoccer" %}
{% set version = "1.6.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/mplsoccer-{{ version }}.tar.gz
  sha256: 02c2a3c4056b0a4d79564f06639c6bc62550a87db22917cd424d5785fc34a15e

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - hatch
    - python {{ python_min }}
    - pip
  run:
    - python >={{ python_min }}
    - matplotlib-base >=3.6
    - numpy
    - pandas
    - pillow
    - requests
    - scipy
    - seaborn

test:
  imports:
    - mplsoccer
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://pypi.org/project/mplsoccer/
  summary: Football pitch plotting library for matplotlib
  dev_url: https://github.com/andrewRowlinson/mplsoccer
  doc_url: https://mplsoccer.readthedocs.io/en/latest/
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - andrewRowlinson
