{% set name = "mplsoccer" %}
{% set version = "1.4.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/mplsoccer-{{ version }}.tar.gz
  sha256: 1c86bababc2922a35fc523431effd2f8158c98d8481a98fa4a1ad126f39e412c

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - hatch
    - python {{ python_min }}
    - pip
  run:
    - python >={{ python_min }}
    - matplotlib-base >=3.6
    - numpy
    - pandas
    - pillow
    - requests
    - scipy
    - seaborn

test:
  imports:
    - mplsoccer
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://pypi.org/project/mplsoccer/
  summary: Football pitch plotting library for matplotlib
  dev_url: https://github.com/andrewRowlinson/mplsoccer
  doc_url: https://mplsoccer.readthedocs.io/en/latest/
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - andrewRowlinson
