{% set name = "mplsoccer" %}
{% set version = "1.8.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://files.pythonhosted.org/packages/source/{{ name[0] }}/{{ name }}/mplsoccer-{{ version }}.tar.gz
  sha256: 77d504d38e19ef310f4a22c95a78572db1e6f1a8f721c7d5535e3623ddada2e8

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - hatch
    - python {{ python_min }}
    - pip
  run:
    - python >={{ python_min }}
    - matplotlib-base >=3.6
    - numpy
    - pandas
    - pillow
    - requests
    - scipy
    - seaborn

test:
  imports:
    - mplsoccer
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://pypi.org/project/mplsoccer/
  summary: Football pitch plotting library for matplotlib
  dev_url: https://github.com/andrewRowlinson/mplsoccer
  doc_url: https://mplsoccer.readthedocs.io/en/latest/
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - andrewRowlinson
