{% set name = "mplsoccer" %}
{% set version = "1.6.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/mplsoccer-{{ version }}.tar.gz
  sha256: 021d5369049d3f3f2aecade7b3a94240e0c2b5458835bdca09421a01ad9d0f15

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - hatch
    - python {{ python_min }}
    - pip
  run:
    - python >={{ python_min }}
    - matplotlib-base >=3.6
    - numpy
    - pandas
    - pillow
    - requests
    - scipy
    - seaborn

test:
  imports:
    - mplsoccer
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://pypi.org/project/mplsoccer/
  summary: Football pitch plotting library for matplotlib
  dev_url: https://github.com/andrewRowlinson/mplsoccer
  doc_url: https://mplsoccer.readthedocs.io/en/latest/
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - andrewRowlinson
